services:
  database:
    container_name: database
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: development
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
