# simple CI workflow
name: Verify Codebase CI

on: push

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '20.11.1' ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit Test
        run: npm t
      - name: Integration Test
        run: npm run test:e2e
